require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.0
  SuggestExtensions: false
  Exclude:
    - '**/db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - config.ru

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false