ignore_unreachable_actions:
  - ^devise\/
  - ^devise_invitable\/
ignore_unused_routes:
  - ^devise\/
  - ^devise_invitable\/
  - rails/conductor/action_mailbox/inbound_emails#edit
  - rails/conductor/action_mailbox/inbound_emails#update
  - rails/conductor/action_mailbox/inbound_emails#update
  - rails/conductor/action_mailbox/inbound_emails#destroy